name: elixir_ci_hex_publish

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.12.0-alpine

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apk add git
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: |
        git config --global --add safe.directory /__w/lowendinsight/lowendinsight
        MIX_ENV=test mix coveralls
        MIX_ENV=test mix docs
    - name: Publish to Hex
      env: # Or as an environment variable
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      if: github.event.pull_request.merged == true
      run: |
        git config --global --add safe.directory /__w/lowendinsight/lowendinsight
        mix hex.publish --yes

